/* geocode-venues.js
   Run manually when adding new venues to venues-registry.json:
     node geocode-venues.js
   Reads venues-registry.json, geocodes any missing lat/lng,
   writes coords back into venues-registry.json directly, and
   rebuilds venues-data.js. Never needs to run on a schedule.
*/
const fs = require('fs');
const path = require('path');

const REGISTRY_PATH = path.join(__dirname, '..', 'venues-registry.json');
const OUTPUT_PATH = path.join(__dirname, '..', 'js', 'venues-data.js');
const API_KEY = process.env.GOOGLE_GEOCODE_API_KEY;

async function geocodeAddress(address) {
  const url = `https://maps.googleapis.com/maps/api/geocode/json?address=${encodeURIComponent(address)}&key=${API_KEY}`;
  const res = await fetch(url);
  const data = await res.json();
  if (data.status !== 'OK') throw new Error(`Geocode failed for "${address}": ${data.status}`);
  return data.results[0].geometry.location; // { lat, lng }
}

(async function main() {
  const venues = JSON.parse(fs.readFileSync(REGISTRY_PATH, 'utf8'));
  let updated = false;

  for (const venue of venues) {
    if (typeof venue.lat === 'number') continue; // already geocoded
    console.log(`Geocoding ${venue.name}...`);
    try {
      const { lat, lng } = await geocodeAddress(venue.address);
      venue.lat = lat;
      venue.lng = lng;
      updated = true;
      console.log(`  → ${lat}, ${lng}`);
    } catch (err) {
      console.warn(`  ✗ ${err.message}`);
    }
  }

  if (updated) {
    // write coords back into the registry so you don't re-geocode next time
    fs.writeFileSync(REGISTRY_PATH, JSON.stringify(venues, null, 2));
    console.log('Updated venues-registry.json with new coordinates.');
  }

  // always re-write venues-data.js from whatever's in the registry
  const output = `/* venues-data.js — generated by geocode-venues.js, do not edit by hand */\nwindow.VENUES = ${JSON.stringify(venues, null, 2)};\n`;
  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, output);
  console.log(`Wrote ${venues.length} venues to ${OUTPUT_PATH}`);
})();